# This rule is not used by the project kalypso itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to calypso.lmoet.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kalypso
    app.kubernetes.io/managed-by: kustomize
  name: compute-viewer-role
rules:
- apiGroups:
  - calypso.lmoet.io
  resources:
  - computes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - calypso.lmoet.io
  resources:
  - computes/status
  verbs:
  - get
