---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - calypso.lmoet.io
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calypso.lmoet.io
  resources:
  - workloads/finalizers
  verbs:
  - update
- apiGroups:
  - calypso.lmoet.io
  resources:
  - workloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kalypso.io
  resources:
  - workloadgraphs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kalypso.io
  resources:
  - workloadgraphs/finalizers
  verbs:
  - update
- apiGroups:
  - kalypso.io
  resources:
  - workloadgraphs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - kro.run
  resources:
  - resourcegraphdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
