apiVersion: calypso.lmoet.io/v1alpha1
kind: Observability
metadata:
  labels:
    app.kubernetes.io/name: kalypso
    app.kubernetes.io/managed-by: kustomize
  name: observability-sample
spec:
  # TODO(user): Add fields here
